### ISSUE TITLE
C99 codegen uses uint16_t internally for queue indexing

### ISSUE THREAD

**Issue by fredyr** [leepike/Copilot#6] opened 2015-06-03 18:10 UTC
We're running Copilot monitoring on an embedded system with a Sharc ADSP-21489. This processor only supports 32-bit words (for example char and int are both represented with 32-bits).

Since the Queue in [copilot-c99 uses `Word16`](https://github.com/leepike/copilot-c99/blob/master/src/Copilot/Compile/C99/Queue.hs#L16) for its queue indexing, this compiles down to `uint16_t` in the generated C code, which our platform compiler doesn't support. (Our work-around right now, which works fine btw, is to define uint16_t in our C header.)

Code to replicate:

```haskell
{-# LANGUAGE RebindableSyntax #-}
import Language.Copilot
import qualified Copilot.Compile.C99 as C

nats :: Stream Word32
nats = [0] ++ nats + 1

spec :: Spec
spec = do
  observer "h" nats

compileSpec = do
  reify spec >>= C.compile C.defaultParams

```

Compilation generates among other

```c
/* copilot.update_state_s0 */
static void __r1() {
  bool __0 = true;
  uint16_t __1 = state.copilot.queue_pointer_str0;
  uint16_t __2 = 0;
  uint16_t __3 = __1 + __2;
  uint16_t __4 = 1;
  uint16_t __5 = __3 % __4;
  uint32_t __6 = state.copilot.queue_buffer_str0[__5];
  uint32_t __7 = 1UL;
  uint32_t __8 = __6 + __7;
  if (__0) {
    __coverage[0] = __coverage[0] | (1 << 1);
  }
  state.copilot.tmp0 = __8;
}
```

**Comment by leepike** [comment] 2015-06-04 05:14
Ok, I see. This may be the most exotic processor Copilot has run on, BTW. :) I think the problem is actually in Atom, which is used to do the code generation.

We made the assumption that the <stdint.h> types would be supported by the compiler/processor, which is generally reasonable.

My inclination is to have folks do a workaround like you did in these fairly rare cases when the assumption is violated. It seems easier than exposing some of these "hidden" types in a config.

Does that sound reasonable?

**Comment by fredyr** [comment] 2015-06-04 06:28
Yes, I think that is definitely reasonable. 

As a side note, I tried changing the 
`type QueueIndexType = Word16` (https://github.com/leepike/copilot-c99/blob/master/src/Copilot/Compile/C99/Queue.hs#L16) in `copilot-c99/Queue` to `Word32` last night, and it removed all references to uint16_t, from all of our use cases at least. 

It would perhaps be interesting to verify if that is the only fixed bit-width assumption inside the code-gen? 

Anyways, thanks for the feed-back -- after looking into the code generation a bit more it now feels more confident to use the work around we have in place.

**Comment by leepike** [comment] 2015-06-04 15:39
Oh, good catch: the size is defined in Copilot, not Atom. It's been a while since I've written the code. As an aside, we were running on an 16-bit Arduino and a 32-bit ARM ourselves, so `uint16_t` seemed to be a reasonable choice here.

> It would perhaps be interesting to verify if that is the only fixed bit-width assumption inside the code-gen?
I believe there are others. It would be good to document them. I'll close this ticket and open another one about doing so.

Thanks!

**Closed by leepike** 2015-06-04 15:39 UTC
